theme = "plain"
icons = "awesome"

[[block]]
block = "custom"
command = "xkbmon -o -u"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%F %T"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
