theme = "plain"
icons = "awesome"

[[block]]
block = "custom"
command = "xkbmon -o -u"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%F %T"

[[block]]
block = "battery"
upower = true
format = "{percentage}% {time}"
