# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# c.content.user_stylesheets = str(config.configdir) + '/themes/dark.css'

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

c.url.searchengines = {
    'DEFAULT': 'https://google.com/?q={}',
    'vic': 'https://la.wikipedia.org/w/index.php?search={}&title=Specialis%3AQuaerere',
    'red': 'https://reddit.com/r/{}',
    'ps': 'https://pursuit.purescript.org/search?q={}',
    'tpb': 'http://thepiratebay.org/search/{}',
    'ghr': 'https://github.com/search?utf8=%E2%9C%93&q={}&type=',
    'ghn': 'https://github.com/search?utf8=%E2%9C%93&q={}+in%3Aname&type=Repositories',
    'ud': 'https://www.urbandictionary.com/define.php?term={}&utm_source=search-action',
    'aw': 'https://wiki.archlinux.org/index.php?title=Special%3ASearch&search={}',
    'yt': 'https://www.youtube.com/results?search_query={}',
    'w': 'https://www.wikipedia.org/search-redirect.php?family=wikipedia&language=en&search={}&language=en&go=Go',
    'sk': 'https://www.skytorrents.in/search/all/ed/1/?l=en-us&q={}',
    'whl': 'https://alpha.wallhaven.cc/search?q={}&categories=111&purity=100&sorting=views&order=desc',
    'whh': 'https://alpha.wallhaven.cc/search?q={}&categories=111&purity=100&atleast=2560x1440&sorting=views&order=desc&page=2',
    'i': 'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
    'ddg': 'https://duckduckgo.com/?q={}&t=ha&iar=images',
}

c.aliases = {
    'gh': "open -t https://github.com/vyorkin"
}

## Background color for webpages if unset (or empty to use the theme's
## color)
## Type: QtColor
c.colors.webpage.bg = 'black'

## How many commands to save in the command history. 0: no history / -1:
## unlimited
## Type: Int
c.completion.cmd_history_max_items = 100
