(use-package shackle
  :init
  (setq
   shackle-default-rule '(:select t)
   shackle-default-alignment 'below
   shackle-default-size 0.4
   shackle-rules
   '((help-mode :align below :select t)
     (helpful-mode :align below)
     (dired-mode :same t)
     (xref--xref-buffer-mode :select t)
     (diff-mode :select t)
     (locate-mode :select t)
     (tabulated-list-mode :noesc t)
     (Buffer-menu-mode :size 0.4 :align below :autoclose t)
     (pomidor :size 0.4 :align below :noselect t)
     (comint-mode :noesc t :align below)
     (grep-mode :size 0.4 :align below :autoclose t)
     (profiler-report-mode :popup t)
     (compilation-mode :select nil :size 0.25)
     ("*compilation*" :select nil :size 0.25)
     ("*golint*" :size 0.5 :noselect t)
     ("*Completions*" :size 0.3 :align t)
     ("*Calendar*" :select t :size 0.3 :align below)
     ("*eshell*" :regexp t :select t :popup t :align below :size 0.2)
     ("*ert*" :same t)
     ("*eww*" :select t :popup t :align below)
     ("*prodigy*" :select t :popup t)
     ("*haskell-compilation" :size 0.25 :align below :noselect t)
     ("*undo-tree*" :size 0.25 :align right :select t)
     (cider-repl-mode :align below :size 0.3)
     ("*cider-error*" :align below :size 0.4)
     ("*Apropos*" :select t :align below :size 0.3)
     ("*Process List*" :select t :align below :size 0.3)
     (flycheck-error-list-mode :select nil :align below :size 0.25)
     ("*Flycheck errors*" :select nil :size 0.25)
     ("*Flycheck error messages*" :select nil :size 0.25)
     ("*Messages*" :select nil :other t)
     ("*Warnings*" :select nil :size 0.25)
     ("*Error*" :select nil :size 0.25)
     ("*dhall-buffer-type-errors*" :noselect t :size 0.1 :inhibit-window-quit t :other t)
     ("*Backtrace*" :select nil :align below :size 0.25)
     ("*Org Links*" :select nil :size 0.2)
     ("*Bookmark List*" :select t :inhibit-window-quit t :same t)
     ("*Geiser documentation*" :select t :align below :size 0.3)
     ("*slime-description*" :select t :align below :size 0.3)
     ("^\\*docker.+\\*$" :regexp t :size 0.3 :select t :align below)
     (neotree-mode :align left)
     (magit-status-mode :align bottom :size 0.5)
     (magit-log-mode :same t :inhibit-window-quit t)
     (magit-commit-mode :ignore t)
     (magit-diff-mode :select nil :align left :size 0.5)
     (git-commit-mode :same t)
     (vc-annotate-mode :same t)
     (ivy-occur-grep-mode :select t :align below :size 0.3)
     ("*tide-documentation*" :select t :align below :size 0.3 :popup t)
     (tide-references-mode :select t :align below :size 0.3)
     ("^\\*git-gutter.+\\*$" :regexp t :size 15 :noselect t)))
  :config
  (shackle-mode 1))

(provide 'init-shackle)
