{:repl {:dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.namespace "0.2.11"]
                       [org.clojure/tools.nrepl "0.2.13"]]}}

{:user {:plugins [[cider/cider-nrepl "0.16.0"]
                  [lein-dotenv "RELEASE"]
                  [lein-exec "0.3.7"]
                  [lein-pprint "1.2.0"]
                  [lein-kibit "0.1.6"]
                  [lein-try "0.4.3"]
                  [jonase/eastwood "0.2.7"]
                  [lein-ancient "0.6.0-SNAPSHOT"]
                  [lein-annotations "0.1.0"]
                  [lein-autoreload "0.1.0"]
                  [lein-bikeshed "0.2.0"]
                  [lein-cprint "1.2.0"]
                  [lein-ns-dep-graph "0.2.0-SNAPSHOT"]
                  [lein-vanity "0.2.0"]
                  [lein-ring "0.9.7"]
                  [lein-cloudbees "1.0.5"]
                  [org.clojure/tools.trace "0.7.9"]
                  [venantius/ultra "0.4.0"]]
        :dependencies [[slamhound "1.5.5"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
