#!/usr/bin/env bash

case $BLOCK_BUTTON in
     2) pamixer -t;;
     4) pamixer -i 5;;
     5) pamixer -d 5;;
esac
code=0
if [[ `pamixer --get-mute` = "true" ]]
then
  volume=""
  end=""
  icon="婢"
else
  volume=`pamixer --get-volume`
  end="%"
  if [[ $volume -lt 33 ]]
  then
    icon="奄"
  else
    if [[ $volume -lt 66 ]]
    then
      icon="奔"
    else
      icon="墳"
      code=33
    fi
  fi
fi
[[ -n $BLOCK_BUTTON ]] && text=" $volume$end"
echo "<span font='Material Icons'>$icon</span>$text"
exit $code
